version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:19.6.0
    steps:
      - checkout
      - run:
          command: npm install
          name: Install
      - run:
          command: npm run lint
          name: Lint
      - run:
          command: npm t
          name: Test

  build:
    docker:
      - image: cimg/node:19.6.0
    steps:
      - checkout
      - run:
          command: npm install
          name: Install
      - run:
          command: npm run build
          name: Build

  publish:
    docker:
      - image: cimg/node:19.6.0
    steps:
      - checkout
      - run:
          command: npm install
          name: Install
      - run:
          command: npm run build
          name: Build
      - run:
          name: publish
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
  test-build:
    jobs:
      - test
      - build:
          requires:
            - test

  tagged-build:
    jobs:
      - publish:
          filters:
          tags:
            only: /v[0-9]+(\.[0-9]+)*/
