version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:19.6.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm ci
          name: Install
      - run:
          command: npm run lint
          name: Lint
      - run:
          command: npm t
          name: Test

  build:
    docker:
      - image: cimg/node:19.6.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build

  publish:
    docker:
      - image: cimg/node:19.6.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
  test-build-publish:
    jobs:
      - test
      - build:
          requires:
            - test
      - hold:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          type: approval
          requires:
            - test
            - build
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - hold
