version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
        command: npm ci
        name: Install
      - run:
        command: npm run lint
        name: Lint
      - run:
        command: npm t
        name: Test

  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
        command: npm run build
        name: Build

  publish:
    steps:
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
  test-build-publish:
    jobs:
      - test
      - build:
          requires:
            - test
      - hold:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          type: approval
          requires:
            - test
            - build
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - hold
